[package]
name = "sak_proofs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sak_crypto = { path = "../sak_crypto" }
sak_logger = { path = "../sak_logger" }
sak_types = { path = "../sak_types" }
log = "0.4.0"
bellman = "0.11.1"
bls12_381 = "0.6.0"
ff = "0.11"
pairing = "0.21.0"
rand = { version = "0.8.4", features = ["getrandom"] }
sha2 = "0.9.8"
env_logger = "0.9.0"
blake2s_simd = "1.0.0"

[dev-dependencies]
sak_test_utils = { path = "../sak_test_utils" }
tokio = { version = "1.12.0", features = ["full"] }

[lib]
doctest = false # until stable beta is released
