[package]
name = "saksaha"
version = "0.1.0"
edition = "2018"
default-run = "sak"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sak_logger = { path = "../sak_logger" }
sak_crypto = { path = "../sak_crypto" }
sak_dist_ledger = { path = "../sak_dist_ledger" }
sak_fs = { path = "../sak_fs" }
sak_proofs = { path = "../sak_proofs" }
sak_p2p_addr = { path = "../sak_p2p_addr" }
sak_p2p_ptable = { path = "../sak_p2p_ptable" }
sak_p2p_id = { path = "../sak_p2p_id" }
sak_p2p_disc = { path = "../sak_p2p_disc" }
sak_p2p_trpt = { path = "../sak_p2p_trpt" }
sak_utils_time = { path = "../sak_utils_time" }
sak_utils_net = { path = "../sak_utils_net" }
sak_task_queue = { path = "../sak_task_queue" }
sak_types = { path = "../sak_types" }
async-trait = "0.1.56"
sak_contract_std = { path = "../sak_contract_std" }
clap = { version = "3.1.6", features = ["cargo"] }
directories = "3.0"
bytes = "1"
rand_core = "0.6.3"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
serde_yaml = "0.8"
serde_bytes = "0.11.6"
rand = "0.8.4"
tokio = { version = "1.12.0", features = ["full"] }
tokio-util = { version = "0.7.2", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
futures = "0.3.17"
thiserror = "1.0"
log = "0.4.0"
env_logger = "0.9.0"
once_cell = "1.8.0"
colored = "2"
chrono = "0.4"
url = { version = "2", features = ["serde"] }
aes = "0.8.1"
hex-literal = "0.3.4"
ctr = "0.9.1"
wasmtime = "0.37.0"

[dev-dependencies]
sha3 = "0.10.1"

[build-dependencies]
chrono = "0.4"
sak_wasm_postprocess = { path = "../sak_wasm_postprocess" }

[[bin]]
name = "sak"
path = "src/bin/sak/main.rs"

[[bin]]
name = "faucet"
path = "src/bin/faucet/main.rs"

[lib]
doctest = false # until stable beta is released
