[package]
name = "sak_task_queue"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sak_logger = { path = "../sak_logger" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
tokio = { version = "1.12.0", features = ["full"] }
futures = "0.3.17"
k256 = { version = "0.9.6", features = ["ecdh"] }
log = "0.4.0"
thiserror = "1.0"
sak_utils_time = { path = "../sak_utils_time" }

[lib]
doctest = false # until stable beta is released
